---
version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - /data/project/php:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - /data/project/php:/code
