---
version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:8090"
    volumes:
      - ./ojs-3.1.1-2:/code
      - ./ojs.conf:/etc/nginx/conf.d/ojs.conf
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./ojs-3.1.1-2:/code

  db:
    image: mysql:5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: lupalagi
       MYSQL_DATABASE: ojs
       MYSQL_USER: ojs
       MYSQL_PASSWORD: passojsppaass
