version: '3'

services:
  logstash:
    build: ./logstash
    depends_on:
      - elasticsearch
      - database
  elasticsearch:
    image: elasticsearch:5.5-alpine
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lupalagi
      MYSQL_DATABASE: testdb
      MYSQL_USER: testdb
      MYSQL_PASSWORD: testdb
